-- 프로젝트 내부에 쿼리를 남겨놔서
-- 다른 컴퓨터에서 환경을 구축할 경우
-- 쉽게 구축이 가능하도록 하자

-- 스프링 시큐리티 적용 전 프로젝트/ 세션이용

-- 회원 정보 테이블
CREATE TABLE MEMBER(
	USERID VARCHAR2(30) PRIMARY KEY, -- 사용자 ID
	USERPW VARCHAR2(100) NOT NULL, -- 사용자 PW
	USERNAME VARCHAR2(30) NOT NULL, -- 사용자 이름
	EMAIL VARCHAR2(50) NOT NULL, -- 이메일 주소
	-- 스프링 시큐리티를 위해 추가
	ENABLED NUMBER(1) DEFAULT 1 CHECK (ENABLED IN (0, 1)), -- 계정상태 1: ENABLED, 0: DISABLED
	ROLENAME VARCHAR2(20) DEFAULT 'ROLE_USER' CHECK (ROLENAME IN ('ROLE_USER', 'ROLE_ADMIN')) -- 계정 권한
);

-- 게시글 정보 테이블
CREATE TABLE BOARD(
	BOARDNUM NUMBER PRIMARY KEY, -- 글 번호
	TITLE VARCHAR2(300) NOT NULL, -- 제목
	CONTENT VARCHAR2(4000) NOT NULL, -- 내용
	-- 참조하고 있는 사용자 ID가 삭제된 경우 해당하는 사용자 ID를 가진 글 정보는 
	-- 모두 따라서 삭제됨 (ON DELETE CASCADE)
	USERID VARCHAR2(30) REFERENCES MEMBER(USERID) ON DELETE CASCADE,
	VIEWCOUNT NUMBER DEFAULT 0, -- 조회수(기본값 0)
	INPUTDATE DATE DEFAULT SYSDATE -- 작성일자(기본값 시스템 시간)
	RECOMMEND NUMBER DEFAULT 0 -- 추천수(중복가능) -- 없어질 얘
	ORIGINALFILE VARCHAR2(1000),
	SAVEDFILE VARCHAR2(1000)
);

-- 게시글 번호를 위환 시퀀스
CREATE SEQUENCE BOARD_SEQ; -- 1부터 시작해서 1씩 증가하하는 시퀀스 생성

-- 댓글 정보 테이블
CREATE TABLE REPLY(
	REPLYNUM NUMBER PRIMARY KEY, -- 댓글 번호
	REPLYTEXT VARCHAR2(1000) NOT NULL, -- 댓글 내용
	USERID VARCHAR2(30) REFERENCES MEMBER(USERID) ON DELETE SET NULL, 
	INPUTDATE DATE DEFAULT SYSDATE, -- 작성 일자
	BOARDNUM NUMBER REFERENCES BOARD(BOARDNUM) ON DELETE CASCADE
);

-- 댓글 번호를 위한 시퀀스
CREATE SEQUENCE REPLY_SEQ;

-- 추천 테이블
CREATE TABLE RECOMMENDATION(
	BOARDNUM NUMBER REFERENCES BOARD(BOARDNUM) ON DELETE CASCADE,
	USERID VARCHAR2(30) REFERENCES MEMBER(USERID) ON DELETE CASCADE
);
